### ISSUE TITLE
LEI-3: Create functionality to replace a BODS v0.2 statement including an additional identifier

### ISSUE THREAD

**Issue by tiredpixel** [openownership/register-sources-oc#13]
### Tasks

- [x] This should mark the previous statement as being replaced
- [x] This should publish a new statement with a new statementID

### Estimate

6h

### References

- _Estimate for adding LEIs identifiers_ (PDF)—
  _T3: Create functionality to replace a BODS v0.2 statement including an additional identifier_
- https://github.com/openownership/register-sources-oc/issues/8

cc @StephenAbbott, @spacesnottabs

**Comment by tiredpixel** [comment]
In consultation with @spacesnottabs, it seems there is nothing left to be done for this issue, since the LEIs were integrated into the existing statement code, meaning that the replacement and publishing of statements should already be handled.

@StephenAbbott, I think we can close this, if you're happy.

**Comment by StephenAbbott** [comment]
@tiredpixel I'm happy so will close it
